((nil . ((indent-tabs-mode . nil)))
 (c-mode . ((c-basic-offset . 4)))
 (nxml-mode . ((fill-column . 100)
               (mode . auto-fill)
               (mode . flyspell)))
 (markdown-mode . ((mode . flyspell)
                   (mode . auto-fill))))
