<?xml version="1.0" encoding="UTF-8" ?>

<!--
    Document   : options-to-html 
    Created on : September 29, 2002 
    Author     : Jens Gulden
    
    Creates a simple HTML-view on all options available to an application, 
    similar to the on generated by GUIApplication.createHelpHTML().
-->

<xsl:stylesheet version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:fo="http://www.w3.org/1999/XSL/Format">

    <xsl:output method="html" indent="yes" encoding="UTF-8"/>
    
    <!--
    <xsl:strip-space elements="..."/>
    <xsl:preserve-space elements="..."/>
    -->

    <!-- template rule matching source root element -->
    
    <xsl:template match="/">
        <xsl:apply-templates select="test-environment"/>
    </xsl:template>
    
    
    <xsl:template match="test-environment">
        <html>
            <head>
                <title>unpaper - Test Protocol</title>
                <link rel="stylesheet" href="img/style.css"/>
            </head>
            <body>
                <!--ol-->
                <xsl:apply-templates select="testcase"/>
                <!--/ol-->
            </body>
        </html>
    </xsl:template>

    <xsl:template match="testcase">
        <!--li-->
        <hr/>
        <h2>[<xsl:value-of select="@id"/>] <xsl:value-of select="@title"/></h2>
        <p class="description">
            <xsl:value-of select="description"/>
        </p>
        
        <!--
        <h3>Input</h3>
        <p>
        <xsl:for-each select="input-file">
            <a href="{substring-before(@name,'.')}.png" target="_blank" onclick="window.open('{substring-before(@name,'.')}.png', '{@name}', 'width=600,toolbar=no,location=no,scrollbars=yes,resizable=yes,status=no');return false"><img class="input" src="img/{substring-before(@name,'.')}.png"/></a>
        </xsl:for-each>        
        </p>
        
        <h3>Output</h3>
        <p>
        <xsl:for-each select="output-file">
            <a href="{substring-before(@name,'.')}.png" target="_blank" onclick="window.open('{substring-before(@name,'.')}.png', '{@name}', 'width=600,toolbar=no,location=no,scrollbars=yes,resizable=yes,status=no');return false"><img class="output" src="img-results/{substring-before(@name,'.')}.png"/></a>
        </xsl:for-each>
        </p>
        -->
        
        <table>
            <tr>
                <td>
                    <h3>Input</h3>
                </td>
                <td width="10%"> </td>
                <td>
                    <h3>Output</h3>
                </td>
            </tr>
            <tr>
                <td>
                    <table>
                        <tr>
                            <xsl:for-each select="input-file">
                                <td>
                                    <a href="img/{substring-before(@name,'.')}.png" target="_blank" onclick="window.open('img/{substring-before(@name,'.')}.png', '{@name}', 'width=600,toolbar=no,location=no,scrollbars=yes,resizable=yes,status=no');return false"><img class="input" src="img/{substring-before(@name,'.')}.png"/></a>
                                    <br/>
                                    <small><xsl:value-of select="@name"/></small>
                                </td>
                            </xsl:for-each>
                        </tr>
                    </table>
                </td>
                <td> </td>
                <td align="left">
                    <table>
                        <tr>
                            <xsl:for-each select="output-file">
                                <td>
                                    <a href="img-results/{substring-before(@name,'.')}.png" target="_blank" onclick="window.open('img-results/{substring-before(@name,'.')}.png', '{@name}', 'width=600,toolbar=no,location=no,scrollbars=yes,resizable=yes,status=no');return false"><img class="output" src="img-results/{substring-before(@name,'.')}.png"/></a>
                                    <br/>
                                    <small><xsl:value-of select="@name"/></small>
                                </td>
                            </xsl:for-each>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
        
        <h3>Options</h3>
        <p class="options">
            unpaper -v --overwrite <xsl:value-of select="options"/>
        </p>
        
        <h3>Verbose Output</h3>
        <p class="output">
            <iframe class="log" src="log/test{@id}.txt" width="600" height="400"/>
        </p>
        <!--/li-->
    </xsl:template>

    <xsl:template match="*" priority="-1"/>

</xsl:stylesheet> 